#!/usr/bin/perl
use strict;
use warnings;

my $data_file = 'data.txt';
open my $fh, '<', $data_file or die "Could not open '$data_file': $!";

my @data;
while (my $line = <$fh>) {
    chomp $line;
    push @data, $line if $line =~ /^\d+(\.\d+)?$/; # Only process valid numbers
}
close $fh;

# Calculate Mean
sub calculate_mean {
    my @arr = @_;
    return 0 unless @arr;
    my $sum = 0;
    $sum += $_ for @arr;
    return $sum / @arr;
}

# Calculate Median
sub calculate_median {
    my @arr = sort { $a <=> $b } @_;
    my $count = @arr;
    return 0 unless $count;
    if ($count % 2 == 1) {
        return $arr[int($count / 2)];
    } else {
        return ($arr[$count / 2 - 1] + $arr[$count / 2]) / 2;
    }
}

# Calculate Mode
sub calculate_mode {
    my @arr = @_;
    return 0 unless @arr;
    my %counts;
    $counts{$_}++ for @arr;
    my $mode;
    my $max_count = 0;
    foreach my $value (keys %counts) {
        if ($counts{$value} > $max_count) {
            $max_count = $counts{$value};
            $mode = $value;
        }
    }
    return $mode;
}

# Print results
print "Data from file: @data\n";
print "Mean: " . calculate_mean(@data) . "\n";
print "Median: " . calculate_median(@data) . "\n";
print "Mode: " . calculate_mode(@data) . "\n";

__END__
# Data for data.txt
2.5
4.1
3.2
5.5
2.5
6.0
4.1
4.1
